services:
  - type: web
    name: elocate-web
    env: node
    plan: free          # choose your plan
    region: oregon       # pick a region
    branch: main         # branch to deploy
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start
    autoDeploy: true     # deploy on each push
    envVars:
      - key: postgresql://elocate_db_user:muwPJSUmlrfYvpfzSO92yzVO5a7l1q6l@dpg-d6m52g7kijhs73e6f9pg-a/elocate_db
        fromDatabase:
          name: elocate-db
          property: connectionString
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        value: "<your token>"
