export default function ReducePage() {
  return (
    <div style={{ padding: 40, maxWidth: 900, margin: "auto" }}>

      <h1 style={{ textAlign: "center" }}>REDUCE</h1>

      <p>
        Reduce means minimizing the amount of electronic waste generated by using
        electronic devices wisely and responsibly. Instead of frequently buying new
        gadgets, people should try to use devices for a longer time.
      </p>

      <p>
        Many electronics are replaced not because they are broken, but because newer
        models are available. By avoiding unnecessary upgrades and purchases, we can
        significantly reduce e-waste.
      </p>

      <p>
        Reducing e-waste also involves choosing durable and high-quality products,
        taking proper care of devices, and repairing them instead of replacing them.
        Using one device for multiple purposes and buying refurbished electronics also helps.
      </p>

      <p>
        Proper recycling further reduces landfill burden and prevents harmful chemicals
        from leaking into soil and water while recovering precious materials.
      </p>

      <h3><u>Benefits of Reducing E-Waste</u></h3>

      <p><b>1. Less Environmental Pollution</b><br/>
      Reduces toxic substances harming soil, air, and water.</p>

      <p><b>2. Conserves Natural Resources</b><br/>
      Saves raw materials and minerals.</p>

      <p><b>3. Protects Human Health</b><br/>
      Lowers exposure to hazardous electronic components.</p>

      <div style={{ textAlign: "center", marginTop: 20 }}>
        <img src="/reduce/images2.jfif" alt="Reduce symbol" width={250} />
      </div>

      <div style={{ textAlign: "center", marginTop: 30 }}>
        <h3>Video on Reduce</h3>

        <iframe
          width="420"
          height="236"
          src="https://www.youtube.com/embed/FcnaYdGdthg"
          allowFullScreen
        />
      </div>

    </div>
  )
}
